name: CI/CD Staging Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Scan backend image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: sravana123/backend:staging
          severity: CRITICAL,HIGH
          exit-code: 0

      - name: Scan frontend image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: sravana123/frontend:staging
          severity: CRITICAL,HIGH
          exit-code: 0

      - name: Build and push backend image
        run: |
          docker build -t sravana123/backend:staging backend
          docker push sravana123/backend:staging

      - name: Build and push frontend image
        run: |
          docker build -t sravana123/frontend:staging frontend
          docker push sravana123/frontend:staging
