- name: Build and push backend image
  run: |
    docker build -t sravana123/backend:staging backend
    docker push sravana123/backend:staging

- name: Build and push frontend image
  run: |
    docker build -t sravana123/frontend:staging frontend
    docker push sravana123/frontend:staging
